### ISSUE TITLE
Discount is calculated incorrectly

### ISSUE THREAD

**Issue by kaberc** [cuba-platform/sample-business-logic#9]
https://github.com/cuba-platform/sample-business-logic/blob/183a468dbb9abe42a268d176fa1362915b2b402e/modules/web/src/com/company/sample/web/ex1/customer/CustomerBrowse.java#L68-L77

"If" statements arranged incorrectly. First of all sum value is compared to 100 and if it's less than 100 the code checks if the value is greater than 200 (always false). Should be in reverse order.

Example of incorrect behaviour:
1. sum of all orders is greater than 200 but less than 300
2. calculate discount

ER: customer discount = 20 * Math.random()
AR: customer discount = 10 * Math.random()

**Comment by knstvk** [comment]
Thank you for noticing!
